# Generated by Django 3.2.13 on 2022-06-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productinstore_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstore',
            old_name='availaible',
            new_name='available',
        ),
    ]
