name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env: 
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker build . --file Dockerfile --tag vineetk1998/anakin-api:latest
        docker login -u vineetk1998 -p $DOCKERHUB_PASS
        docker push vineetk1998/anakin-api:latest

  
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    
    steps:
    - name: Deploy to cluster
      uses: ianbelcher/eks-kubectl-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_DEPLOY_REGION }}
        cluster_name: ${{ secrets.AWS_CLUSTER_NAME }}
        args: rollout restart deployment anakin-api -n anakin

